# Generated by Django 2.2.7 on 2019-12-01 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191128_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
