# Generated by Django 2.2.7 on 2019-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
    ]
